name: simple_dart_date_field
description: Date Field Component
version: 0.0.1
repository: https://github.com/simple-dart/date_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.2
